# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d7f4ece2702aa9fac0c6633b85a5325528c5e75c097cd666f39c5de074a84f9621dbd92e9379bd32d8daab34a4bfc4f0215ef8ac714953f82833741207af0ff

test:
  secret_key_base: 35a2cd9f04ac4abdd7a1f6a32ee16fd19969cb88b3ca5cfc700df850890eda153fbb1afd5296511a3247e1d6b9f8114e3aa941d84bbce8c39793ea1d1e342ed9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
